export const GET_RECENT_ACTIONS = {
  GET: 'DATA:GET',
  GET_SUCCESS: 'DATA:GET:SUCCESS',
  GET_FAILURE: 'DATA:GET:FAILURE'
};

export const SPEED_TEST_ACTIONS = {
  GET: 'SPEED:GET',
  GET_SUCCESS: 'SPEED:GET:SUCCESS',
  GET_FAILURE: 'SPEED:GET:FAILURE'
};

export default { GET_RECENT_ACTIONS, SPEED_TEST_ACTIONS };
